<a href="https://colab.research.google.com/github/Gupta-Vaishali/Song-Genre-Classification/blob/main/HyperP_AI_project_Textual_words.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

```
Dataset name : english_cleaned_lyrics.csv
The attributes are : 
Unnamed 0 : This attribute is of no value to us.
Index : This attribute contains the index no. for each record.
Song : This attribute contains the name of the song.
Year : This attribute contains the year the song was released.
Artist : This attribute contains the name of the artist of the song.
Lyrics : This attribute contains the lyrics of the song.
Genre : This attribute specifies the genre of the song. This is the target variable.

Aim of project : Song Genre Classification and 
                Quantitative Sentiment Analysis of Lyrics in Popular Music

ML Task Type : Classification.
```

In [ ]:
# Path of dataset
path = "/content/drive/MyDrive/sample_df.csv"

In [ ]:
# Importing required modules
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt

```
Dataset Loading and Preprocessing
```

In [ ]:
# Loading csv into df
df=pd.read_csv(path)             
df.head()

   Unnamed: 0  ...                                    expanded_lyrics
0           0  ...  oh baby know be gon na cut right chase women m...
1           1  ...  playin everythe easy be like seem sure still w...
2           2  ...  search tendernes be hard find love need live l...
3           3  ...  oh oh oh oh oh oh write book stand title book ...
4           4  ...  party people people party be pop sit around se...

[5 rows x 17 columns]

In [ ]:
# Deleting columns - Unnamed:0 and index
#del df['Unnamed: 0']                
df.head()

              song  ...                                    expanded_lyrics
0        ego-remix  ...  oh baby know be gon na cut right chase women m...
1     then-tell-me  ...  playin everythe easy be like seem sure still w...
2          honesty  ...  search tendernes be hard find love need live l...
3  you-are-my-rock  ...  oh oh oh oh oh oh write book stand title book ...
4    black-culture  ...  party people people party be pop sit around se...

[5 rows x 16 columns]

In [ ]:
temp = df
temp['word_count'] = df['lemmatized_lyrics'].apply(lambda x: len(str(x).split(" ")))
temp

                               song  ...  word_count
0                         ego-remix  ...         229
1                      then-tell-me  ...         129
2                           honesty  ...          82
3                   you-are-my-rock  ...         264
4                     black-culture  ...         189
...                             ...  ...         ...
218204    who-am-i-drinking-tonight  ...         185
218205                         liar  ...         119
218206                  last-supper  ...         126
218207  christ-alone-live-in-studio  ...          87
218208                         amen  ...         194

[218209 rows x 17 columns]

In [ ]:
del temp['lyrics']

In [ ]:
temp['char_count'] = df["lemmatized_lyrics"].apply(lambda x: sum(len(word) for word in str(x).split(" ")))
temp

                               song  ...  word_count
0                         ego-remix  ...         229
1                      then-tell-me  ...         129
2                           honesty  ...          82
3                   you-are-my-rock  ...         264
4                     black-culture  ...         189
...                             ...  ...         ...
218204    who-am-i-drinking-tonight  ...         185
218205                         liar  ...         119
218206                  last-supper  ...         126
218207  christ-alone-live-in-studio  ...          87
218208                         amen  ...         194

[218209 rows x 16 columns]

In [ ]:
temp['unique words'] = df['uniquewords'].apply(lambda x: len(str(x).split(",")))
temp['unique word density'] = temp['unique words'] / temp['word_count']
temp['avg_word_length'] = temp['char_count'] / temp['word_count']
temp

                               song  year  ... unique word density avg_word_length
0                         ego-remix  2009  ...            0.388646        3.772926
1                      then-tell-me  2009  ...            0.519380        4.248062
2                           honesty  2009  ...            0.743902        4.878049
3                   you-are-my-rock  2009  ...            0.287879        3.712121
4                     black-culture  2009  ...            0.126984        4.005291
...                             ...   ...  ...                 ...             ...
218204    who-am-i-drinking-tonight  2012  ...            0.502703        4.486486
218205                         liar  2012  ...            0.453782        4.176471
218206                  last-supper  2012  ...            0.571429        4.103175
218207  christ-alone-live-in-studio  2012  ...            0.643678        4.919540
218208                         amen  2012  ...            0.376289        4.134021

[218209 rows x 18 columns]

In [ ]:
import sys  
!{sys.executable} -m pip install contractions

Collecting contractions
  Downloading https://files.pythonhosted.org/packages/0a/04/d5e0bb9f2cef5d15616ebf68087a725c5dbdd71bd422bcfb35d709f98ce7/contractions-0.0.48-py2.py3-none-any.whl
Collecting textsearch>=0.0.21
  Downloading https://files.pythonhosted.org/packages/d3/fe/021d7d76961b5ceb9f8d022c4138461d83beff36c3938dc424586085e559/textsearch-0.0.21-py2.py3-none-any.whl
Collecting anyascii
  Downloading https://files.pythonhosted.org/packages/a3/14/666cd44bf53f36a961544af592cb5c5c800013f9c51a4745af8d7c17362a/anyascii-0.2.0-py3-none-any.whl (283kB)
     |████████████████████████████████| 286kB 8.5MB/s
Collecting pyahocorasick
  Downloading https://files.pythonhosted.org/packages/7f/c2/eae730037ae1cbbfaa229d27030d1d5e34a1e41114b21447d1202ae9c220/pyahocorasick-1.4.2.tar.gz (321kB)
     |████████████████████████████████| 327kB 35.0MB/s
Building wheels for collected packages: pyahocorasick
  Building wheel for pyahocorasick (setup.py) ... done
  Created wheel for pyahocorasick: filename=pyahocorasick-1.4.2-cp37-cp37m-linux_x86_64.whl size=85391 sha256=5b0b3a147048dab38806148420c35a9570fbacf700160261c92e4489e44efcdb
  Stored in directory: /root/.cache/pip/wheels/3a/03/34/77e3ece0bba8b86bfac88a79f923b36d805cad63caeba38842
Successfully built pyahocorasick
Installing collected packages: anyascii, pyahocorasick, textsearch, contractions
Successfully installed anyascii-0.2.0 contractions-0.0.48 pyahocorasick-1.4.2 textsearch-0.0.21

In [ ]:
# Expanding contractions

import contractions
# creating an empty list
contraction = []
exp_lyrics = []
for i in df.index: 
  exp_lyrics.append(contractions.fix(str(df.loc[i,'lemmatized_lyrics'])))
  contraction.append(len(str(exp_lyrics[i]).split(' ')) - len(str(df.loc[i,'lemmatized_lyrics']).split(' ')))
  
df['no_of_contractions'] = contraction
df['expanded_lyrics'] = exp_lyrics
df.head(20)

                      song  ...                                    expanded_lyrics
0                ego-remix  ...  oh baby know be gon na cut right chase women m...
1             then-tell-me  ...  playin everythe easy be like seem sure still w...
2                  honesty  ...  search tendernes be hard find love need live l...
3          you-are-my-rock  ...  oh oh oh oh oh oh write book stand title book ...
4            black-culture  ...  party people people party be pop sit around se...
5   all-i-could-do-was-cry  ...  hear church bell ring hear choir sing see love...
6       once-in-a-lifetime  ...  another day would spend waitin right one stare...
7                  waiting  ...  wait wait wait wait wait wait wait wait wait w...
8                slow-love  ...  read magazine wait around say can be wait see ...
9    why-don-t-you-love-me  ...  n n honey better sit look around because must ...
10           save-the-hero  ...  lay alone awake night sorrow fill eye be stron...
11               telephone  ...  hello hello baby call ca be hear thing get ser...
12         ice-cream-truck  ...  feel like be lose mind love hard find lead bel...
13  no-broken-hearted-girl  ...  you are everythe think never nothe like think ...
14                 control  ...  get ta give quite storm rage inside way hit da...
15           i-m-alone-now  ...  really hurt say ye sweet love ai be enough man...
16                  poison  ...  be bad clearly get be see somethe good can com...
17        world-wide-women  ...  be world wide woman www log anywhere be girl t...
18          beautiful-liar  ...  ay ay ay nobody like play oh beyonce beyonce o...
19  beautiful-liar-spanish  ...  ay ay nobody like play ay oh beyonc beyonc oh ...

[20 rows x 21 columns]

In [ ]:
temp['expanded_word_count'] = df["expanded_lyrics"].apply(lambda x: sum(len(word) for word in str(x).split(" ")))
del temp['expanded_lyrics']
temp['contraction_difference'] = temp['expanded_word_count'] - temp['word_count']
temp['contraction_density'] = temp['contraction_difference'] / temp['word_count']
temp

                               song  ...  contraction_density
0                         ego-remix  ...             2.860262
1                      then-tell-me  ...             3.271318
2                           honesty  ...             3.878049
3                   you-are-my-rock  ...             2.727273
4                     black-culture  ...             3.005291
...                             ...  ...                  ...
218204    who-am-i-drinking-tonight  ...             3.502703
218205                         liar  ...             3.201681
218206                  last-supper  ...             3.198413
218207  christ-alone-live-in-studio  ...             3.919540
218208                         amen  ...             3.134021

[218209 rows x 20 columns]

In [ ]:
del temp['no_of_contractions']

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
  
# Encode labels in column 'species'.
temp['genre_id']= label_encoder.fit_transform(temp['genre'])
temp['genre_id'] += 1
temp['genre_id'].unique()

array([ 9,  4, 11,  7,  8,  1,  6,  2,  3, 10,  5])

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
  
# Encode labels in column 'species'.
temp['artist_id']= label_encoder.fit_transform(temp['artist'])
temp['artist_id'] += 1
temp['artist_id'].unique()

array([2663, 7438, 1701, ..., 5763, 6335, 7525])

In [ ]:
temp

                               song  year  ... genre_id artist_id
0                         ego-remix  2009  ...        9      2663
1                      then-tell-me  2009  ...        9      2663
2                           honesty  2009  ...        9      2663
3                   you-are-my-rock  2009  ...        9      2663
4                     black-culture  2009  ...        9      2663
...                             ...   ...  ...      ...       ...
218204    who-am-i-drinking-tonight  2012  ...        1      7525
218205                         liar  2012  ...        1      7525
218206                  last-supper  2012  ...        1      7525
218207  christ-alone-live-in-studio  2012  ...        1      7525
218208                         amen  2012  ...        1      7525

[218209 rows x 21 columns]

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()                   # try with standard scalar
temp_norm = pd.DataFrame(scaler.fit_transform(temp.loc[:,['artist_id','genre_id','word_count','contraction_difference','year','contraction_density','unique word density','char_count','unique words','avg_word_length','expanded_word_count']]),columns=['artist_id','genre_id','word_count','contraction_difference','year','contraction_density','unique word density','char_count','unique words','avg_word_length','expanded_word_count'])
temp_norm.head()

   artist_id  genre_id  ...  avg_word_length  expanded_word_count
0   0.255225       0.8  ...         0.089449             0.064046
1   0.255225       0.8  ...         0.104776             0.039893
2   0.255225       0.8  ...         0.125098             0.028940
3   0.255225       0.8  ...         0.087488             0.071299
4   0.255225       0.8  ...         0.096945             0.054834

[5 rows x 11 columns]

In [ ]:
temp_norm.corr()

                        artist_id  ...  expanded_word_count
artist_id                1.000000  ...            -0.030438
genre_id                -0.012817  ...            -0.246104
word_count              -0.032281  ...             0.987760
contraction_difference  -0.029746  ...             0.998924
year                    -0.006053  ...             0.030553
contraction_density      0.003250  ...            -0.036601
unique word density      0.016422  ...            -0.266492
char_count              -0.030299  ...             0.999870
unique words            -0.019254  ...             0.897108
avg_word_length          0.004444  ...            -0.048390
expanded_word_count     -0.030438  ...             1.000000

[11 rows x 11 columns]

**Naive Bayes**

In [ ]:
from sklearn.model_selection import train_test_split
cols=['word_count',	'char_count',	'unique words',	'unique word density',	'avg_word_length',	'expanded_word_count',	'contraction_difference',	'contraction_density',	'artist_id']
x=temp_norm[cols]
print("Original sape of input dataset",x.shape)                              #shape of original dataset 
y=temp['genre']
print("Original sape of output dataset",y.shape)                        #shape of original dataset
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30)

Original sape of input dataset (218209, 9)
Original sape of output dataset (218209,)

In [ ]:
print("X_train.shape = ",x_train.shape)
print("X_test.shape = ",x_test.shape)

X_train.shape =  (152746, 9)
X_test.shape =  (65463, 9)

In [ ]:
x_train

        word_count  char_count  ...  contraction_density  artist_id
199060         239         863  ...             2.610879       6013
68455           50         248  ...             3.960000       4891
216485         116         469  ...             3.043103       6790
22274          130         608  ...             3.676923       2296
120403         148         644  ...             3.351351       3845
...            ...         ...  ...                  ...        ...
775            120         533  ...             3.475000       7459
63648          213         878  ...             3.159624       3301
182786          79         316  ...             3.000000       4615
169873         185         872  ...             3.713514       4335
37374           91         400  ...             3.395604       5371

[152746 rows x 9 columns]

In [ ]:
y_train

83210     Country
103169       Rock
167862       Rock
129202      Metal
154453        Pop
           ...
129695       Rock
9308         Rock
152402    Hip-Hop
169858       Rock
82892       Metal
Name: genre, Length: 152746, dtype: object

In [ ]:
l = [float(i)/len(df) for i in df['genre'].value_counts()]

In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(x_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
y_pred = classifier.predict(x_test)

In [ ]:
# Predicting the Test set results
print('Accuracy of MultiNB classifier on test set: {:.4f}'.format(metrics.accuracy_score(y_test, y_pred)))
print('F1score of MultiNB classifier on test set: {:.6f}'.format(metrics.f1_score(y_test, y_pred,average='weighted')))

Accuracy of MultiNB classifier on test set: 0.4588
F1score of MultiNB classifier on test set: 0.288687

In [ ]:
# Making the Confusion Matrix
labels = classifier.classes_
conf_df = pd.DataFrame(metrics.confusion_matrix(y_test, y_pred), columns=labels, index=labels)
conf_df.index.name = 'True labels'
conf_df

             Country  Electronic  Folk  Hip-Hop  ...  Other  Pop  R&B   Rock
True labels                                      ...
Country            0           0     0        0  ...      0    0    0   4217
Electronic         0           0     0        0  ...      0    0    0   2093
Folk               0           0     0        1  ...      0    0    0    533
Hip-Hop            0           0     0        4  ...      0    0    0   6720
Indie              0           0     0        0  ...      0    0    0    894
Jazz               0           0     0        0  ...      0    0    0   2195
Metal              0           0     0        1  ...      0    0    0   6376
Other              0           0     0        0  ...      0    0    0   1166
Pop                0           0     0        0  ...      0    0    0  10206
R&B                0           0     0        0  ...      0    0    0   1024
Rock               0           0     0        3  ...      0    0    0  30030

[11 rows x 11 columns]

In [ ]:
from sklearn import metrics
print('Accuracy of Mutlinomial Naive Bayes classifier on test set: {:.4f}'.format(metrics.accuracy_score(y_test, y_pred)))

Accuracy of Mutlinomial Naive Bayes classifier on test set: 0.5090

In [ ]:
# Classification report of the multinomial naive bayes classifier
print(metrics.classification_report(y_test, y_pred, target_names=classifier.classes_))

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

              precision    recall  f1-score   support

     Country       0.00      0.00      0.00      4357
  Electronic       0.18      0.03      0.06      2137
        Folk       0.00      0.00      0.00       521
     Hip-Hop       0.66      0.71      0.68      6842
       Indie       0.00      0.00      0.00       861
        Jazz       0.00      0.00      0.00      2226
       Metal       0.42      0.33      0.37      6292
       Other       0.00      0.00      0.00      1140
         Pop       0.31      0.21      0.25     10243
         R&B       0.00      0.00      0.00       967
        Rock       0.53      0.81      0.64     29877

    accuracy                           0.51     65463
   macro avg       0.19      0.19      0.18     65463
weighted avg       0.40      0.51      0.44     65463

**Decision Tree**

In [ ]:
# Fitting Decision Tree Classification to the Training set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy',random_state = 0)
classifier.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [ ]:
# Predicting the Test set results
y_pred = classifier.predict(x_test)

In [ ]:
# Making the Confusion Matrix
labels = classifier.classes_
cm = pd.DataFrame(metrics.confusion_matrix(y_test, y_pred), columns=labels, index=labels)
cm.index.name = 'True labels'
cm

             Country  Electronic  Folk  Hip-Hop  ...  Other   Pop  R&B   Rock
True labels                                      ...
Country         3264          39    16       96  ...     50   191   11    518
Electronic        50        1035    14      103  ...     51   166   15    504
Folk              12          12   260       22  ...      8    32    3    122
Hip-Hop           88         108    23     5187  ...     72   328   17    768
Indie             17          18     6       29  ...     23    69    5    192
Jazz              63          34     4       52  ...     49   128    5    307
Metal             96         143    47      200  ...     63   322   34   1439
Other             37          37    15       89  ...    331   148   10    336
Pop              185         154    46      336  ...    161  7270   54   1516
R&B               14          20     2       26  ...     15    52  675    110
Rock             470         520   106      779  ...    341  1524  124  24042

[11 rows x 11 columns]

In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7314513542000824

In [ ]:
print(metrics.classification_report(y_test, y_pred, target_names=classifier.classes_))

              precision    recall  f1-score   support

     Country       0.76      0.75      0.75      4357
  Electronic       0.49      0.48      0.49      2137
        Folk       0.48      0.50      0.49       521
     Hip-Hop       0.75      0.76      0.75      6842
       Indie       0.50      0.51      0.50       861
        Jazz       0.69      0.68      0.69      2226
       Metal       0.61      0.61      0.61      6292
       Other       0.28      0.29      0.29      1140
         Pop       0.71      0.71      0.71     10243
         R&B       0.71      0.70      0.70       967
        Rock       0.81      0.80      0.81     29877

    accuracy                           0.73     65463
   macro avg       0.62      0.62      0.62     65463
weighted avg       0.73      0.73      0.73     65463

In [ ]:
from sklearn.externals.six import StringIO  
from IPython.display import Image  
from sklearn.tree import export_graphviz
import pydotplus

dot_data = StringIO()

export_graphviz(classifier, out_file=dot_data,  filled=True, rounded=True, special_characters=True)

graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
Image(graph.create_png())

In [ ]:
print(df['genre'].value_counts())

Rock          100053
Pop            34137
Hip-Hop        22654
Metal          21210
Country        14158
Jazz            7309
Electronic      6942
Other           3786
R&B             3336
Indie           2935
Folk            1689
Name: genre, dtype: int64

In [ ]:
d = {}
n = ['Rock','Pop','Hip-Hop','Metal',"Country",'Jazz','Electronic','Other','R&B','Indie','Folk']
i = 0 
for i in range(11):
  d[n[i]] = l[i]

In [ ]:
from sklearn.linear_model import SGDClassifier
logReg = SGDClassifier(class_weight=d)

In [ ]:
logReg.fit(x_train, y_train)

SGDClassifier(alpha=0.0001, average=False,
              class_weight={'Country': 0.06488275002405951,
                            'Electronic': 0.03181353656356979,
                            'Folk': 0.007740285689407861,
                            'Hip-Hop': 0.10381789935337223,
                            'Indie': 0.01345040763671526,
                            'Jazz': 0.033495410363458884,
                            'Metal': 0.09720039045135627,
                            'Other': 0.017350338437003055,
                            'Pop': 0.15644175996407114,
                            'R&B': 0.015288095358119968,
                            'Rock': 0.45851912615886603},
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [ ]:
y_pred = logReg.predict(x_test)

In [ ]:
print('Accuracy of LogReg classifier on test set: {:.4f}'.format(metrics.accuracy_score(y_test, y_pred)))
print('F1score of LogReg classifier on test set: {:.6f}'.format(metrics.f1_score(y_test, y_pred,average='weighted')))

Accuracy of LogReg classifier on test set: 0.0403
F1score of LogReg classifier on test set: 0.018329

In [ ]:
print(metrics.classification_report(y_test, y_pred, target_names=classifier.classes_))

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

              precision    recall  f1-score   support

     Country       0.00      0.00      0.00      4176
  Electronic       0.00      0.00      0.00      2078
        Folk       0.00      0.00      0.00       504
     Hip-Hop       0.77      0.65      0.71      6849
       Indie       0.00      0.00      0.00       916
        Jazz       0.00      0.00      0.00      2126
       Metal       0.55      0.17      0.26      6403
       Other       0.00      0.00      0.00      1092
         Pop       0.44      0.09      0.15     10293
         R&B       0.00      0.00      0.00       980
        Rock       0.51      0.94      0.66     30046

    accuracy                           0.53     65463
   macro avg       0.21      0.17      0.16     65463
weighted avg       0.44      0.53      0.43     65463

In [ ]:
from sklearn.linear_model import LogisticRegression
logReg = LogisticRegression(max_iter=1000,penalty='l1',warm_start=True,solver='saga',multi_class='multinomial',class_weight=d)

In [ ]:
logReg.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)

LogisticRegression(C=1.0,
                   class_weight={'Country': 0.06488275002405951,
                                 'Electronic': 0.03181353656356979,
                                 'Folk': 0.007740285689407861,
                                 'Hip-Hop': 0.10381789935337223,
                                 'Indie': 0.01345040763671526,
                                 'Jazz': 0.033495410363458884,
                                 'Metal': 0.09720039045135627,
                                 'Other': 0.017350338437003055,
                                 'Pop': 0.15644175996407114,
                                 'R&B': 0.015288095358119968,
                                 'Rock': 0.45851912615886603},
                   dual=False, fit_intercept=True, intercept_scaling=1,
                   l1_ratio=None, max_iter=1000, multi_class='multinomial',
                   n_jobs=None, penalty='l1', random_state=None, solver='saga',
                   tol=0.0001, verbose=0, warm_start=True)

In [ ]:
y_pred = logReg.predict(x_test)

In [ ]:
print('Accuracy of logistic regression classifier on test set: {:.4f}'.format(logReg.score(x_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.5015

In [ ]:
print(metrics.classification_report(y_test, y_pred, target_names=classifier.classes_))

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

              precision    recall  f1-score   support

     Country       0.00      0.00      0.00      4357
  Electronic       0.00      0.00      0.00      2137
        Folk       0.00      0.00      0.00       521
     Hip-Hop       0.77      0.65      0.71      6842
       Indie       0.00      0.00      0.00       861
        Jazz       0.00      0.00      0.00      2226
       Metal       0.56      0.17      0.26      6292
       Other       0.00      0.00      0.00      1140
         Pop       0.44      0.09      0.15     10243
         R&B       0.00      0.00      0.00       967
        Rock       0.51      0.95      0.66     29877

    accuracy                           0.53     65463
   macro avg       0.21      0.17      0.16     65463
weighted avg       0.43      0.53      0.42     65463

In [ ]:
from sklearn.linear_model import LogisticRegression
logReg = LogisticRegression(max_iter=700,l1_ratio=0.3,penalty='elasticnet',warm_start=True,solver='saga',tol=0.001)

In [ ]:
logReg.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=10, l1_ratio=0.3, max_iter=700,
                   multi_class='auto', n_jobs=None, penalty='elasticnet',
                   random_state=None, solver='saga', tol=0.001, verbose=0,
                   warm_start=True)

In [ ]:
y_pred = logReg.predict(x_test)

In [ ]:
from sklearn import metrics
print('Accuracy of logistic regression classifier on test set: {:.4f}'.format(metrics.accuracy_score(y_test, y_pred)))

Accuracy of logistic regression classifier on test set: 0.5149

In [ ]:
print(metrics.classification_report(y_test, y_pred, target_names=classifier.classes_))

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

              precision    recall  f1-score   support

     Country       0.00      0.00      0.00      4357
  Electronic       0.00      0.00      0.00      2137
        Folk       0.00      0.00      0.00       521
     Hip-Hop       0.77      0.65      0.71      6842
       Indie       0.00      0.00      0.00       861
        Jazz       0.00      0.00      0.00      2226
       Metal       0.56      0.17      0.26      6292
       Other       0.00      0.00      0.00      1140
         Pop       0.43      0.09      0.15     10243
         R&B       0.00      0.00      0.00       967
        Rock       0.51      0.95      0.66     29877

    accuracy                           0.53     65463
   macro avg       0.21      0.17      0.16     65463
weighted avg       0.43      0.53      0.42     65463

In [ ]:
from sklearn.linear_model import SGDClassifier
classifier = SGDClassifier(loss='modified_huber',penalty='elasticnet',l1_ratio=0.5,alpha=0.00001,warm_start=True)

In [ ]:
classifier.fit(x_train, y_train)

SGDClassifier(alpha=1e-05, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.5, learning_rate='optimal', loss='modified_huber',
              max_iter=1000, n_iter_no_change=5, n_jobs=None,
              penalty='elasticnet', power_t=0.5, random_state=None,
              shuffle=True, tol=0.001, validation_fraction=0.1, verbose=0,
              warm_start=True)

In [ ]:
y_pred = classifier.predict(x_test)

In [ ]:
from sklearn import metrics
print('Accuracy of SGD classifier on test set: {:.4f}'.format(metrics.accuracy_score(y_test, y_pred)))
print('Accuracy of SGD classifier on test set: {:.4f}'.format(metrics.f1_score(y_test, y_pred,average='weighted')))

Accuracy of SGD classifier on test set: 0.5246
Accuracy of SGD classifier on test set: 0.4017

In [ ]:
print(metrics.classification_report(y_test, y_pred, target_names=classifier.classes_))

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

              precision    recall  f1-score   support

     Country       0.00      0.00      0.00      4357
  Electronic       0.50      0.00      0.00      2137
        Folk       0.00      0.00      0.00       521
     Hip-Hop       0.59      0.75      0.66      6842
       Indie       0.00      0.00      0.00       861
        Jazz       0.01      0.00      0.00      2226
       Metal       0.63      0.03      0.06      6292
       Other       0.00      0.00      0.00      1140
         Pop       0.40      0.02      0.04     10243
         R&B       0.00      0.00      0.00       967
        Rock       0.51      0.94      0.66     29877

    accuracy                           0.51     65463
   macro avg       0.24      0.16      0.13     65463
weighted avg       0.43      0.51      0.38     65463

In [ ]:
# Fitting Decision Tree Classification to the Training set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'gini',random_state = 0,max_depth=45,class_weight='balanced',max_leaf_nodes=40000)#max_depth=100,80,50

In [ ]:
classifier.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight='balanced', criterion='gini',
                       max_depth=45, max_features=None, max_leaf_nodes=40000,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [ ]:
# Predicting the Test set results
y_pred = classifier.predict(x_test)

In [ ]:
# Making the Confusion Matrix
labels = classifier.classes_
cm = pd.DataFrame(metrics.confusion_matrix(y_test, y_pred), columns=labels, index=labels)
cm.index.name = 'True labels'
cm

             Country  Electronic  Folk  Hip-Hop  ...  Other   Pop  R&B   Rock
True labels                                      ...
Country         3756          22     9       72  ...     33    96    4    282
Electronic        25        1337     7       99  ...     33   135    5    343
Folk               5          10   343       18  ...      8    24    1     75
Hip-Hop           83          96    15     5368  ...     98   306   20    648
Indie             12           8     8       15  ...     19    34    1    140
Jazz              34          17     1       32  ...     21    80    6    161
Metal             68          79    34      195  ...     61   242   18   1046
Other             26          33     9       97  ...    482   119    3    262
Pop               88         141    24      296  ...    131  8068   31   1104
R&B               10          10     2       20  ...      7    28  797     71
Rock             228         357    64      632  ...    251  1059   59  25969

[11 rows x 11 columns]

In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print('F1score of SGD classifier on test set: {:.6f}'.format(metrics.f1_score(y_test, y_pred,average='weighted')))

Accuracy: 0.8096023708048822
F1score of SGD classifier on test set: 0.809425

In [ ]:
print(metrics.classification_report(y_test, y_pred, target_names=classifier.classes_))

              precision    recall  f1-score   support

     Country       0.87      0.86      0.86      4357
  Electronic       0.63      0.63      0.63      2137
        Folk       0.66      0.66      0.66       521
     Hip-Hop       0.78      0.78      0.78      6842
       Indie       0.68      0.69      0.68       861
        Jazz       0.82      0.81      0.82      2226
       Metal       0.72      0.71      0.72      6292
       Other       0.42      0.42      0.42      1140
         Pop       0.79      0.79      0.79     10243
         R&B       0.84      0.82      0.83       967
        Rock       0.86      0.87      0.87     29877

    accuracy                           0.81     65463
   macro avg       0.74      0.73      0.73     65463
weighted avg       0.81      0.81      0.81     65463